services:
  - type: web
    name: civic-sense
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /opt/render/project/uploads
      sizeGB: 1
